### PR TITLE
Fix some warnings from GCC 12 and Clang 15

### PR DESCRIPTION
**Pull request by gruenich**
I used `-Wall` and `-pedantic`.

### CODE REVIEW

**Review by DrTimothyAldenDavis — COMMENTED** [review]
Actually, the original is the intent, as:

#define restrict GB_restrict

 I'd like to use the "restrict" keyword throughout the code internally, but some compilers don't like it.  So I #define a GB_restrict in GraphBLAS.h, depending on the compiler.  Then in Source/GB.h, I #define restrict as GB_restrict.

I don't export this #define restrict to the user code.  It's just for internal usage.

Does this cause a warning?

**Review by DrTimothyAldenDavis — COMMENTED** [review]
Make sense, but it might be simpler just to remove the semicolon from the macro definitions, rather than removing the semicolons you have removed.  I'm used to adding semicolons at the end of all lines of code, so removing them looks odd to me.

**Review by DrTimothyAldenDavis — APPROVED** [review]
Good catch.  The original is confusing.

**Comment by DrTimothyAldenDavis** [comment]
Oops.  I meant to merge just one commit for one file (the confusing parentheses).  I'll back out the merge and fix things another way.

**Comment by gruenich** [comment]
I will prepare a new merge request following your comments.

**Comment by gruenich** [comment]
> I don't export this #define restrict to the user code. It's just for internal usage.
> 
> Does this cause a warning?

With `-pedantic -Wall` one of the compilers warned that this define shadows `restrict`.

**Comment by DrTimothyAldenDavis** [comment]
I'm more comfortable fixing this on my end, just because some of the decisions on how to silence these warnings are more of a matter of style.   I appreciate the PR and the fix, but I'm making these changes right now already so I don't need you to update the PR.  I'm finding some more of these kinds of errors too.

**Comment by DrTimothyAldenDavis** [comment]
For the restrict redefinition ... the whole point is to shadow the restrict keyword for compilers that don't support it (like C++ for example, or MS Visual Studio which insists on using "__restrict" instead).  I could use GB_restrict instead, throughout the code, but it makes for ugly code.  I like to see "restrict" throughout the code, and assume that the compiler can handle it (and then patch it with a #define if it doesn't).  So I really don't want to change that.

**Comment by DrTimothyAldenDavis** [comment]
It would be best to get -pedantic -Wall to be silent on this shadowing of the restrict keyword, but I'm not sure how to do that while at the same time patching up the keyword when it's not supported.

**Pull request merged**
