### PR TITLE
update cpu_features

### PR DESCRIPTION
**Pull request by loongson-zjl**
# update cpu_features

*  Update from https://github.com/google/cpu_features.git and commit id is fd4ffc1632db7b4e763bd28ffa6fc9d761cf3587
*  Modify Source for cpu_features update.

### CODE REVIEW

**Comment by DrTimothyAldenDavis** [comment]
Is there a problem with the current version of cpu_features currently used in GraphBLAS that this PR fixes?

**Comment by DrTimothyAldenDavis** [comment]
If there are no critical fixes from this update that affect GraphBLAS, I need to wait until GraphBLAS and SuiteSparse/GraphBLAS becomes stable (after the v9.0.0 release of GraphBLAS).  I have too many variants of GraphBLAS up in the air just now:  see the comments here: https://github.com/DrTimothyAldenDavis/GraphBLAS/pull/225 .

When that becomes stable, I will update my copy of cpu_features to their latest stable release (currently v0.8.0 it seems).

**Comment by loongson-zjl** [comment]
> Is there a problem with the current version of cpu_features currently used in GraphBLAS that this PR fixes?
Yes ,  the new cpu_features can  support   riscv loongarch s390.

**Comment by DrTimothyAldenDavis** [comment]
GraphBLAS doesn't have any specialized code for that platform, however.  All I need from cpu_features is a test to determine if AVX2 and/or AVX512 are available, on the x86 architecture (Intel or AMD).  This update to cpu_features isn't the most recent stable version, which is v0.8.0.  I will update sometime in the future, but not to this version.

**Pull request closed without merging**
